name: tenant_1
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:5432/tenant_1
  username: admin
  password: admin
  hikari:
    poolName: Hikari
    auto-commit: false

spring:
  jpa:
    hibernate:
      ddl-auto=update:
